version: "1.0.0"
services:
    university:
        build: .
        ports:
            - "3015:3015"
        links:
            - university-mysql
    university-mysql: 
        image: mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456789
            - MYSQL_DATABASE=university
        volumes:
            - university-data:/var/lib/mysql
volumes:
    university-data: 